[package]
name = "prima"
version = "0.1.1"
authors = ["Fishykins <caspar.m.green@gmail.com>"]
edition = "2018"

[lib]
name = "prima"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "^0.12.0"
num = "^0.3.0"
image = "^0.23.6"
imageproc = "^0.22.0"
rusttype = "^0.9.2"
obj-rs = "^0.6.1"
ordered-float = "^2.0.0"
rand = "^0.7.3"