[package]
name = "prima"
version = "0.1.0"
authors = ["Fishykins <caspar.m.green@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.12.0"
num = "0.3.0"
image = "0.22.4"
obj-rs = "0.6.1"